# Generated by Django 5.2.7 on 2025-10-04 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_stationconnection_routegraph_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Boarding time')),
                ('exited_at', models.DateTimeField(blank=True, null=True, verbose_name='Exit time')),
                ('is_active', models.BooleanField(default=True, help_text='Whether user is still on this journey')),
                ('journey', models.ForeignKey(help_text='The journey user is currently on', on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='transport.journey', verbose_name='Journey')),
                ('user', models.OneToOneField(help_text='User can only be on one journey at a time', on_delete=django.db.models.deletion.CASCADE, related_name='current_journey', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Journey passenger',
                'verbose_name_plural': 'Journey passengers',
                'ordering': ['-boarded_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='transport_j_user_id_e37a60_idx'), models.Index(fields=['journey', 'is_active'], name='transport_j_journey_8874cd_idx')],
            },
        ),
    ]
