# Generated by Django 5.2.7 on 2025-10-04 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_journeypassenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('DELAY', 'Delay (train stopped or moving slowly)'), ('TECHNICAL_FAILURE', 'Technical failure (vehicle, signaling, switches)'), ('RANDOM_EVENT', 'Random event (accident, passenger illness)'), ('INFRASTRUCTURE', 'Infrastructure issues (track maintenance, blocked crossing)'), ('OVERCROWDING', 'Overcrowding (no seats, very crowded)'), ('WEATHER', 'Weather conditions (snow, storm, heat affecting operations)'), ('COMMUNITY_INFO', 'Community information (lost/found items, passenger assistance)'), ('OTHER', 'Other')], default='OTHER', help_text='Category of the reported issue', max_length=30, verbose_name='Report category'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='category',
            field=models.CharField(choices=[('DELAY', 'Delay (train stopped or moving slowly)'), ('TECHNICAL_FAILURE', 'Technical failure (vehicle, signaling, switches)'), ('RANDOM_EVENT', 'Random event (accident, passenger illness)'), ('INFRASTRUCTURE', 'Infrastructure issues (track maintenance, blocked crossing)'), ('OVERCROWDING', 'Overcrowding (no seats, very crowded)'), ('WEATHER', 'Weather conditions (snow, storm, heat affecting operations)'), ('COMMUNITY_INFO', 'Community information (lost/found items, passenger assistance)'), ('OTHER', 'Other')], default='OTHER', help_text='Category of the reported issue', max_length=30, verbose_name='Report category'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='journey_passenger',
            field=models.ForeignKey(blank=True, help_text='Proves user is currently on the journey', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='transport.journeypassenger', verbose_name='Journey passenger record'),
        ),
    ]
