# Generated by Django 5.2.7 on 2025-10-04 20:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_report_category_userreport_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='average_delay_minutes',
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_staff_reported',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user_reports_count',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='total_confirmations_given',
        ),
        migrations.AddField(
            model_name='report',
            name='confidence_level',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='How confident the user is about this report (0-1)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Confidence level'),
        ),
        migrations.AddField(
            model_name='report',
            name='delay_minutes',
            field=models.IntegerField(blank=True, help_text="User's reported delay duration", null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Delay in minutes'),
        ),
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo evidence of the issue', null=True, upload_to='reports/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='report',
            name='is_staff_report',
            field=models.BooleanField(default=False, help_text='Whether this report is from verified staff (more credible)', verbose_name='Staff report'),
        ),
        migrations.AddField(
            model_name='report',
            name='journey_passenger',
            field=models.ForeignKey(blank=True, help_text='Proves user is currently on the journey', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='transport.journeypassenger', verbose_name='Journey passenger record'),
        ),
        migrations.AddField(
            model_name='report',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='User location latitude'),
        ),
        migrations.AddField(
            model_name='report',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='User location longitude'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Reporting user'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, help_text="User's description of the issue", verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='report',
            name='journey',
            field=models.ForeignKey(blank=True, help_text='Specific journey this report is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='transport.journey', verbose_name='Journey'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='confirmed_reports',
            field=models.IntegerField(default=0, help_text='Reports that were verified by admins', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of confirmed reports'),
        ),
        migrations.DeleteModel(
            name='UserReport',
        ),
    ]
