# Generated by Django 5.2.7 on 2025-10-04 21:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0006_remove_report_average_delay_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=20, verbose_name='Reputation points')),
                ('tier', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Trusted'), (3, 'Experienced'), (4, 'Expert')], default=1, verbose_name='Reputation tier')),
                ('total_reports_created', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total reports created')),
                ('total_feedbacks_given', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total feedbacks given')),
                ('positive_feedbacks_received', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Positive feedbacks received')),
                ('negative_feedbacks_received', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Negative feedbacks received')),
                ('negative_points_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Negative points count')),
                ('last_activity_date', models.DateTimeField(blank=True, null=True, verbose_name='Last activity date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User reputation',
                'verbose_name_plural': 'User reputations',
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='ReportFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('POSITIVE', 'Confirm'), ('NEGATIVE', 'Reject')], max_length=10, verbose_name='Feedback type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='transport.report', verbose_name='Report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Report feedback',
                'verbose_name_plural': 'Report feedbacks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report', 'feedback_type'], name='userstats_r_report__12fbb8_idx'), models.Index(fields=['-created_at'], name='userstats_r_created_66c128_idx')],
                'unique_together': {('report', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ReputationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_change', models.IntegerField(verbose_name='Points change')),
                ('points_after', models.IntegerField(verbose_name='Points after')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reputation history',
                'verbose_name_plural': 'Reputation histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='userstats_r_user_id_f25f66_idx')],
            },
        ),
    ]
